language: python
sudo: enabled
python:
  - "3.6"

install:
  - sudo pip install pytest
  - sudo pip install pylint

script:
  - pytest
  - pylint -E generate_instructions
  - pylint -E generate_instructions_test
